spring:
  datasource:
    url: jdbc:postgresql://${FILE_CLOUD_DB_HOST}:${FILE_CLOUD_DB_PORT}/${FILE_CLOUD_DB_NAME}
    username: ${FILE_CLOUD_DB_USERNAME}
    password: ${FILE_CLOUD_DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
logging:
  level:
    org:
      springframework:
        security: debug
minio:
  user_id: minio
  secret_key: miniosecret
  endpoint: http://127.0.0.1:9000